### ISSUE TITLE
Is it suitable to switch to official `pypika` for `tortoise-orm`

### ISSUE THREAD

**Issue by elisong** [tortoise/pypika-tortoise#1]
Realize `tortoise-orm` depends on this repo instead of [pypika](https://github.com/kayak/pypika) just now ! Even though it gives much more freedom for `tortoise-orm`, but much extra pressure for author. It seems little behind of official one. 

Should I pull [a same requests](https://github.com/kayak/pypika/pull/631) here ? So that remove [the patch](https://github.com/tortoise/tortoise-orm/pull/888) from tortoise-orm.

**Comment by long2ice** [comment]
We need more ability to customize
