### ISSUE TITLE
UpdateQuery produces invalid SQL statement on Joins

### ISSUE THREAD

**Issue by MarcoMuellner** [tortoise/pypika-tortoise#3]
Say you have a query like this:

```python
await Student.all().update(school=school2)
```

this will produce 

```sql
UPDATE "student" SET "school_id"=?
```

It will also work perfectly fine if we filter on the same table, like so:
```python
Student.filter(name='test').update(school=school2).as_query()
```

which produces

```sql
UPDATE "student" SET "school_id"=? WHERE "name"='test'
```

However, if we join a table to filter on for the update, it gets the order wrong. So this

```python
Student.filter(school__id=school2.id).update(name="test").as_query()
```

produces 

```sql
UPDATE "student" 
LEFT OUTER JOIN "school" "student__school" ON "student__school"."id"="student"."school_id" 
SET "name"=? 
WHERE "student__school"."id"=2048
```

The correct sql statement for this would be 

```sql 
UPDATE "student" 
SET "name"=? 
FROM "student"
LEFT OUTER JOIN "school" "student__school" ON "student__school"."id"="student"."school_id" 
WHERE "student__school"."id"=2048
```

I did some digging, and the querybuilder seems to be the issue here, hence me opening an issue on this repo. This also relates to this issue on the main repo https://github.com/tortoise/tortoise-orm/issues/1081

**Comment by MarcoMuellner** [comment]
Thank you <3

**Comment by long2ice** [comment]
I see which is same as origin repo, https://github.com/kayak/pypika/blob/master/pypika/tests/test_updates.py#L48, what's the reason?

**Comment by MarcoMuellner** [comment]
With some further digging, this appears to be correct for MySQL but not for Postgres and SQLite?

Yes i just stumbled upon that myself, but then again, it isn't correct for Postgres nor SQLite.

**Comment by MarcoMuellner** [comment]
If you point me the right way I'd like to help. Would need some guidance though

**Comment by long2ice** [comment]
You can install latest souce code then test in tortoise-orm, wait feedback

**Comment by long2ice** [comment]
In fact keep join is easier, you can try again

**Comment by MarcoMuellner** [comment]
Sadly that doesn't work yet though. I get a ambigious column error with the following statement:

```sql
UPDATE "student" 
SET "name"=? 
FROM "student" 
LEFT OUTER JOIN "school" "student__school" ON "student__school"."id"="student"."school_id" 
WHERE "student__school"."id"=2048
```

On `student.school_id`, due to the statement "student" twice, which makes it suspect to me. I do think the update statement above without the join is the correct one and the one that shjould be used

**Comment by long2ice** [comment]
What's the error? And please show me the table sql so I can test in local

**Comment by MarcoMuellner** [comment]
I get the following error:

```
tortoise.exceptions.OperationalError: ambiguous column name: student.school_id
```

The table is generated from this model (see tortoise orm testing suite)

```python
class School(Model):
    uuid = fields.UUIDField(pk=True)
    name = fields.TextField()
    id = fields.IntField(unique=True)

    students: fields.ReverseRelation["Student"]
    principal: fields.ReverseRelation["Principal"]


class Student(Model):
    id = fields.IntField(pk=True)
    name = fields.TextField()
    school: fields.ForeignKeyRelation[School] = fields.ForeignKeyField(
        "models.School", related_name="students", to_field="id"
    )
```

To test it i use the `test_relations_with_unique.py`testing suite, by adding 
```python
await Student.filter(school__id=school2.id).update(name="test")
```

below line 34.

**Comment by MarcoMuellner** [comment]
Here are the SQL DDL statements:

```sql
create table school
(
    uuid uuid    not null
        primary key,
    name text    not null,
    id   integer not null
        unique
);
```

```
create table student
(
    id        serial
        primary key,
    name      text    not null,
    school_id integer not null
        references school (id)
            on delete cascade
);
```
