### ISSUE TITLE
Rename library

### ISSUE THREAD

**Issue by PromyLOPh** [tortoise/pypika-tortoise#5]
Since this library is an incompatible fork of pypika it would be good if the package directory, which is currently called pypika, would be renamed. Otherwise the original pypika and tortoise-orm conflict when installed into the same environment. Even better would be a [namespace package](https://packaging.python.org/en/latest/guides/packaging-namespace-packages/) in which this pypika fork lives under the tortoise namespace, since – realistically – it won’t be used by anyone else anyway.

**Comment by DavideGalilei** [comment]
Hi @long2ice, is there any plan to move the pypika namespace? I'm currently facing some issue due to the libraries conflict. Also, it is missing a py.typed and mypy complains when importing it. Thanks in advance.

**Comment by waketzheng** [comment]
@abondar @henadzit Is it a good solution that rename `pypika` to `pypika_tortoise` and apply the new package name in `tortoise-orm`?
